# polymorphism = many form - one thing will take into many forms....
# there are four ways of implementing the poloymorphism
# Duck typing, operator overloading, Method Overloading, Method Overriding...